name: Gradle Build
on: [ push, pull_request ]

jobs:
  build:
    uses: okocraft/workflows/.github/workflows/gradle.yml@v1
    with:
      java-version: '21'
      build-arguments: "build"
      package-name: FoliaRegionVisualizer-Build-${{ github.run_number }}
